# Chapter 2: Linear Algebra


In [1]:
import numpy as np

## Numpy Arrays

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[4, 2, 7],
              [6, 2, 1],
              [-5, -2, -4]])
c = np.array([[1, -1, 0],
              [2, 2, 1],
              [-4, -6, -1]])

## Matrix Multiplation Is Not Commutative

In [3]:
print("a@b \n", np.matmul(a, b), "b@c\n", np.matmul(b, c))

a@b 
 [[ 1  0 -3]
 [16  6  9]
 [31 12 21]] b@c
 [[-20 -42  -5]
 [  6  -8   1]
 [  7  25   2]]


## Matrix Multiplication Is Associative

In [4]:
print("(a@b)@c\n", (np.matmul(np.matmul(a, b), c)))

(a@b)@c
 [[  13   17    3]
 [  -8  -58   -3]
 [ -29 -133   -9]]


In [5]:
print("a@(b@c)\n", np.matmul(a, np.matmul(b, c)))

a@(b@c)
 [[  13   17    3]
 [  -8  -58   -3]
 [ -29 -133   -9]]
